package com.adam.gamingserver.services;

import com.adam.gamingserver.model.Game;
import com.adam.gamingserver.repository.GameRepository;
import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class GameService {

    @Autowired // This means to get the bean called gameRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private GameRepository repository;

    public Game save(Game game) {
        return repository.save(game);
    }

    public boolean delete(Game game) {
        try {
            repository.delete(game);
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    public Optional<Game> findOne(long id) {
        return repository.findById(id);
    }

    public List<Game> findAll() {
        return (List<Game>) repository.findAll();
    }

    public float playGame(Game game, float wager) {
        float result = game.playGame(wager);
        return result;
    }
}