package com.adam.gamingserver.services;

import com.adam.gamingserver.model.User;
import com.adam.gamingserver.repository.UserRepository;
import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class UserService {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository repository;

    public User save(User user) {
        return repository.save(user);
    }

    public boolean delete(User user) {
        try {
            repository.delete(user);
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    public Optional<User> findOne(long id) {
        return repository.findById(id);
    }

    public List<User> findAll() {
        return (List<User>) repository.findAll();
    }

    public String login(long id, String password) {
        Optional<User> user = repository.findById(id);
        if (!user.isPresent()) {
            return "noaccess";
        }
        String access = user.get().login(user.get().getEmail(), password);
        return access;
    }
}